@startuml

!include /1ce-icons-for-plantuml/dist/common.puml
!include /1ce-icons-for-plantuml/dist/all.puml

'header
title Система управления проектами
caption Схема объектов системы
footer Софт-Юнити, 2023

_Справочник(Проекты, "Проекты")
_Документ(Требование, "Требование") 

package "Актирование" <<Cloud>> {
    _Справочник(Контрагенты, "Контрагенты"){
        Код : Строка(9)
        Наименование : Строка(100)
        ПолноеНаименование : Строка
        ИНН : Строка(50)
        КПП : Строка(9)
    }

    _Справочник(ДоговорыКонтрагентов, "Договоры контрагентов"){
        Владелец : Контрагенты
        Код : Строка(9)
        Наименование : Строка(100)
    }
    Контрагенты --> ДоговорыКонтрагентов::Владелец

    _Справочник(Заказы, "Заказы"){
        Владелец : ДоговорыКонтрагентов
        Проект : Проекты
    }
    ДоговорыКонтрагентов --> Заказы::Владелец
    Проекты --> Заказы::Проект

    _Перечисление(ВидыАктированияТребований, "Виды актирования требований") {
        НеПривязаноКЗаказу
        ВЗаказе
        КАктированию
        Актировано
    }
    _РегистрСведений(АктированиеТребований, "Актирование требований"){
        Непереодический, независимый
        <$d> Требование : Требование
        <$r> Актирование : ВидыАктированияЗадач
     }
    ВидыАктированияТребований --> АктированиеТребований: Актирование
    Требование --> АктированиеТребований: Требование

    _Документ(Актирование, "Актирование"){
        Контрагент : Контрагент
        Заказ : Заказы
        __Требования__
        Требование : Требование
        ПолностьюАктировать : Булево
    }
    Контрагенты --> Актирование: Контрагент
    Заказы --> Актирование: Заказ
    Требование --> Актирование: Требование

    _РегистрСведений(ТребованияВЗаказах, "ТребованияВЗаказах"){
        Непереодический, независимый
        <$d> Требование : Требование (ведущее) 
        <$d> Заказ : Заказ
     }
    Требование --> ТребованияВЗаказах: Требование
    Заказы --> ТребованияВЗаказах: Заказ

   note as N1
    В форме документа требования создаем реквизит формы
    который показывает текущее состояние актирования.
    Если текущее состояние - "В заказе" то рядом появляется кнопка "К актированию"
    при нажатии на нее треобование переходит в в состояние "КАктированию"
    При создании нового требования - статус НеПривязаноКЗаказу
    При записи в регистр сведений "ТреованияВЗаказах" проверяем, если для 
    требования есть хоть 1 запись тогда меняем статус требования на
    "В заказе"
    При проведении документа "Актирование", если галочка "ПолностьюАктировать"
    стоит тогда в регистре "АктированиеТребований" ставим статус "Актировано"
    end note

}

@enduml