@startuml

title Система управления проектами
caption Актуализация статусов задачи
footer Софт-Юнити, 2023

start
:Создание задачи;
:По-умолчанию статус: "Не начато"
На форме кнопки «Взять в работу» и «Отменить»;
if (Нажали кнопку) then ("Отменить")
: Задача переходит в статус "Отменена";
stop
else ("Взять в работу")
switch ( ТипЗадачи )
case ( Тестирование )
: Задача переходит в статус "В работе";
: На форме кнопки "Тестирование успешно",
"Тестирование не успешно",  "Приостановить", "Отменить";
switch (Нажата кнопка)
case ("Тестирование успешно")
    : Задача переходит в статус "Выполнена";
case ("Тестирование не успешно")
    : Задача переходит в статус "Выполнена";
    : Новая задача для на основании. Тип задачи : "Исправление";
case ("Приостановить")
    : Задача переходит в статус "Приостановлена";
case ("Отменить")
    : Задача переходит в статус "Отменена";
    stop
endswitch
case ( Разработка )
: Задача переходит в статус "В работе";
: На форме кнопки "Выполнено", "Приостановить", "Отменить";
switch (Нажата кнопка)
case ("Выполнено")
    : Задача переходит в статус "Выполнена";
case ("Приостановить")
    : Задача переходит в статус "Приостановлена";
case ("Отменить")
    : Задача переходит в статус "Отменена";
    stop
endswitch
case ( Все остальное )
: Задача переходит в статус "В работе";
: На форме кнопки "Выполнено", "Приостановить", "Отменить";
switch (Нажата кнопка)
case ("Выполнено")
    : Задача переходит в статус "Выполнена";
case ("Приостановить")
    : Задача переходит в статус "Приостановлена";
case ("Отменить")
    : Задача переходит в статус "Отменена";
    stop
endswitch
endswitch

endif

if (Статус задачи) then (Выполнена) 
    :Задача заблокирована для редактирования;
else (Приостановлена)
    :Задача заблокирована для редактирования. 
    Доступна кнопка "Вернуть в работу" при нажатии на нее статус "В работе";
endif

@enduml