@startuml

!include /1ce-icons-for-plantuml/dist/common.puml
!include /1ce-icons-for-plantuml/dist/all.puml

'header
title Система управления проектами
caption Схема объектов системы
footer Софт-Юнити, 2023

_Справочник(Проекты, "Проекты")
_Документ(Задача, "Задача") 

package "Актирование" <<Cloud>> {
    _Справочник(Контрагенты, "Контрагенты"){
        Код : Строка(9)
        Наименование : Строка(100)
        ПолноеНаименование : Строка
        ИНН : Строка(50)
        КПП : Строка(9)
    }

    _Справочник(ДоговорыКонтрагентов, "Договоры контрагентов"){
        Владелец : Контрагенты
        Код : Строка(9)
        Наименование : Строка(100)
    }
    Контрагенты --> ДоговорыКонтрагентов::Владелец

    _Справочник(Заказы, "Заказы"){
        Владелец : ДоговорыКонтрагентов
        Проект : Проекты
    }
    ДоговорыКонтрагентов --> Заказы::Владелец
    Проекты --> Заказы::Проект

    _Перечисление(ВидыАктированияЗадач, "Виды актирования задач") {
        ВЗаказе
        Кактированию
        Актировано
    }
    _РегистрСведений(АктированиеЗадач, "Актирование задач"){
        <$d> Задача : Задача
        <$r> Актирование : ВидыАктированияЗадач
     }
    ВидыАктированияЗадач --> АктированиеЗадач: Актирование
    Задача --> АктированиеЗадач: Задача

    _Документ(Актирование, "Актирование"){
        Контрагент : Контрагент
        Заказ : Заказы
        __Задачи__
        Задача : Задача
    }
    Контрагенты --> Актирование: Контрагент
    Заказы --> Актирование: Заказ
    Задача --> Актирование: Задача


}

@enduml