@startuml

!include /1ce-icons-for-plantuml/dist/common.puml
!include /1ce-icons-for-plantuml/dist/all.puml

'header
title Система управления проектами
caption Бюджетная оценка
footer Софт-Юнити, 2023

_Справочник(СтадииТребований, "Стадии")
_Справочник(Пользователи, "Пользователи") 
_Справочник(Проекты, "Проекты")
_Справочник(ЭтапыПроектов, "Этапы проектов")
_Справочник(КатегорииСпециалистов, "Категории специалистов")
_Документ(Требование, "Требование")
_Документ(Задача, "Задача") 

package "Бюджетная оценка" <<Cloud>> {

_Справочник(ВерсииБюджетныхОценок, "Версии оценки") {
    Требование : Требование
    ДатаВерсии : Дата(Дата + Время)
    Автор : Пользователи
}
Требование --> ВерсииБюджетныхОценок::Требование
Пользователи --> ВерсииБюджетныхОценок::Автор

_РегистрСведений(БюджетнаяОценка, "Бюджетная оценка"){
    {abstract} Непереодический, независимый
    __
    <$d> ВерсияОценки : ВерсииБюджетныхОценок
    <$d> Проект : Проекты
    <$d> ЭтапПроекта : ЭтапыПроектовв
    <$d> Требование : Требование
    <$d> Стадия : СтадииТребований
    <$d> Задача : Задача
    <$d> КатегорияСпециалиста : КатегорииСпециалистов
    <$r> Часы: Число (10, 2)
}
ВерсииБюджетныхОценок --> БюджетнаяОценка::ВерсияОценки
Проекты --> БюджетнаяОценка::Проект
ЭтапыПроектов --> БюджетнаяОценка::ЭтапПроекта
Задача --> БюджетнаяОценка::Задача
Требование --> БюджетнаяОценка::Требование
КатегорииСпециалистов --> БюджетнаяОценка::КатегорияСпециалиста
СтадииТребований --> БюджетнаяОценка::Стадия

}




@enduml