@startuml

title Система управления проектами
caption Процесс создания проекта
footer Софт-Юнити, 2023

start
:Создаем элемент справочника "Проекты";
:Заполняем все необходимые реквизиты, записываем элемент;
if (Ведется учет в разрезе этапов проекта) then (Да)
    : Создаем подчиненные элементы справочника "Этапы проекта";
else (Нет)
endif
:Заполняем связанные регистры сведений
"Категории специалистов проектов"
"Этапы требований проектов"
"Сотрудники проектов"
"Статьи бюджета проектов"
"Системы проектов"
"Функциональные блоки проектов"
"Виды времени проектов";
stop

@enduml