@startuml

!include /1ce-icons-for-plantuml/dist/common.puml
!include /1ce-icons-for-plantuml/dist/all.puml

'header
title Система управления проектами
caption Бюджетная оценка
footer Софт-Юнити, 2023

_Документ(Требование, "Требование")
_Документ(Задача, "Задача")
_Справочник(Пользователи, "Пользователи")

package "История комментариев" <<Cloud>> {

_РегистрСведений(ИсторияКомменатриев, "История комментариев") {
    {abstract} Независимый, переодичность в пределах секунды
    --
    <$d> Объект : Определяемы тип (ПредметКомментирования)
    <$d> Автор : Пользователь
    <$r> Комментарий: Строка()
}

Задача --> ИсторияКомменатриев::Объект
Требование --> ИсторияКомменатриев::Объект
Пользователи --> ИсторияКомменатриев::Автор

note as N1
  Необходимо разработать некую
  подсистему хранения комментариев
  что бы ее можно было подключать к объектам
  Для это используем определеяемый тип и аналогично 
  подсистеме "дополнительные реквизиты и сведения" 
  добавляем динамически панель и прочее на форму
end note

}


@enduml