@startuml

!include /1ce-icons-for-plantuml/dist/common.puml
!include /1ce-icons-for-plantuml/dist/all.puml

title Система управления проектами
caption Карта ввода на основании
footer Софт-Юнити, 2023

_Справочник(Проекты)
_Справочник(ЭтапыПроектов)

_Документ(Требование)
_Документ(Задача)
_Документ(РабочийОчет)

Проекты --> Требование
ЭтапыПроектов --> Требование
Задача --> Задача
Требование --> Задача

Проекты --> РабочийОчет
Задача --> РабочийОчет
Требование --> РабочийОчет

@enduml

