@startuml

!include /1ce-icons-for-plantuml/dist/common.puml
!include /1ce-icons-for-plantuml/dist/all.puml

'header
title Система управления проектами
caption Проект и настройка проекта
footer Софт-Юнити, 2023

_Справочник(Контрагенты, "Контрагенты"){
}

_Справочник(ВидыВремени, "Виды времени") {
    Рабочее : Булево
}

_Справочник(СтатьиБюджета, "Статьи бюджета")
_Справочник(Системы, "Системы")
_Справочник(ФункциональныеБлоки, "Функциональные блоки")

_Перечисление(ВидыОсновныхЗадач, "Виды основных задач"){
    УстанавливаетсяВручную
    Аналитика
    УправлениеРазаработкой
    УправлениеПроектом
    НеСоздаются
}

_Справочник(СтадииТребований, "Стадии требований"){
    {abstract} Предопределенные элементы
    __
    Бэклог : ВидОсновнойЗадачи - УстанавливаетсяВручную
    БезЭтапа : ВидОсновнойЗадачи - УстанавливаетсяВручную
    ПодтверждениеРП : ВидОсновнойЗадачи - УправлениеПроектом
    Завершено : ВидОсновнойЗадачи - НеСоздаются
    __
    ВидОсновнойЗадачи: ВидыОсновныхЗадач
}

ВидыОсновныхЗадач --> СтадииТребований::ВидОсновнойЗадачи

_Справочник(Проекты, "Проекты"){
    {abstract} Необходимо подключить механизм доп. реквизитов
    __
    Владелец : Контрагенты
    Административный : Булево
    УчетПоЭтапам : Булево
}

_Справочник(ЭтапыПроектов, "Этапы проектов"){
    {abstract}Иерархический справочник
    __
    Владелец : Проекты
}

_Справочник(Сотрудники, "Сотрудники"){
    Должность : Должности
    --КатегорииСотрудника--
    КатегорияСпециалиста : КатегорииСпециалистов
}

_Справочник(КатегорииСпециалистов, "Категории специалистов"){
}

_РегистрСведений(КатегорииСпециалистовПроектов, "Категории специалистов проектов") {
    {abstract} Непереодический, независимый
    __
    <$d> Проект : Проекты
    <$d> КатегорияСпециалиста: КатегорииСпециалистов
}

_РегистрСведений(СотрудникиПроектов, "Сотрудники проектов") {
    {abstract} Непереодический, независимый
    __
    <$d> Проект : Проекты
    <$d> Сотрудник: Сотрудники
}

_РегистрСведений(СтатьиБюджетаПроектов, "Статьи бюджета проектов") {
    {abstract} Непереодический, независимый
    __
    <$d> Проект : Проекты
    <$rd> СтатьяБюджета: СтатьиБюджета
}

_РегистрСведений(СистемыПроектов, "Системы проектов") {
    {abstract} Непереодический, независимый
    __
    <$d> Проект : Проекты
    <$d> Система: Системы
}

_РегистрСведений(ФункциональныеБлокиПроектов, "Функциональные блоки проектов") {
    {abstract} Непереодический, независимый
    __
    <$d> Проект : Проекты
    <$d> ФункциональныйБлок: ФункциональныеБлоки
}

_РегистрСведений(ВидыВремениПроектов, "Виды времени проектов") {
    {abstract} Непереодический, независимый
    __
    <$d> Проект : Проекты
    <$d> ВидВремени: ВидыВремени
}

_РегистрСведений(РелизыСистемПроектов, "Релизы систем проектов"){
    {abstract} Непереодический, независимый
    __
    <$d> Проект : Проекты
    <$d> Система : Системы
    <$r> Релиз: Строка (50)
}

_РегистрСведений(СтадииТребованийПроектов, "Стадии требований проектов"){
    {abstract} Непереодический, независимый
    __
    <$d> Проект : Проекты
    <$d> Стадия : Стадии
    <$r> Порядок : Число(3)
}

_Справочник(Должности, "Должности")

Контрагенты --> Проекты::Владелец

Сотрудники --> СотрудникиПроектов::Сотрудник

Проекты --> РелизыСистемПроектов::Проект
Проекты --> ЭтапыПроектов::Владелец
Проекты --> ВидыВремениПроектов::Проект
Проекты --> ФункциональныеБлокиПроектов::Проект
Проекты --> СистемыПроектов::Проект
Проекты --> СтатьиБюджетаПроектов::Проект
Проекты --> СотрудникиПроектов::Проект
Проекты --> КатегорииСпециалистовПроектов::Проект
Проекты --> СтадииТребованийПроектов::Проект

СтадииТребований --> СтадииТребованийПроектов::Стадия

СтатьиБюджета --> СтатьиБюджетаПроектов::СтатьяБюджета

Системы --> СистемыПроектов::Система
Системы --> РелизыСистемПроектов::Система

ВидыВремени --> ВидыВремениПроектов::ВидВремени

КатегорииСпециалистов --> КатегорииСпециалистовПроектов::КатегорияСпециалиста

ФункциональныеБлоки --> ФункциональныеБлокиПроектов::ФункциональныйБлок

Должности --> Сотрудники::Должность

@enduml