@startuml

!include /1ce-icons-for-plantuml/dist/common.puml
!include /1ce-icons-for-plantuml/dist/all.puml

'header
title Система управления проектами
caption Проект и настройка проекта
footer Софт-Юнити, 2023

_Справочник(Контрагенты, "Контрагенты")
_Перечисление(ТипыЗадач, "Типы задач")
_Справочник(Сотрудники, "Сотрудники")
_Справочник(КатегорииСпециалистов, "Категории специалистов")

package "Настройка проекта" <<Cloud>> {

    _Справочник(ВидыВремени, "Виды времени")
    _Справочник(СтатьиБюджета, "Статьи бюджета")
    _Справочник(Системы, "Системы")
    _Справочник(ФункциональныеБлоки, "Функциональные блоки")

    _Справочник(Проекты, "Проекты"){
        {abstract} Необходимо подключить механизм доп. реквизитов
        __
        Владелец : Контрагенты
        Административный : Булево
        УчетПоЭтапам : Булево
    }
    Контрагенты --> Проекты:Владелец

    _Справочник(ЭтапыПроектов, "Этапы проектов"){
        {abstract}Иерархический справочник
        __
        Владелец : Проекты
    }
    Проекты --> ЭтапыПроектов:Владелец

    _Справочник(СтадииТребований, "Стадии требований"){
        {abstract} Предопределенные элементы
        __
        Бэклог : ТипЗадач
        БезСтадии : ТипЗадач
        ПодтверждениеРП : ТипЗадач
        Завершено : ТипЗадач - НеСоздаются
        __
        ТипЗадач: ТипыЗадач
        СоздаватьЗадачи: Булево
        Оценивать : Булево
    }
    ТипыЗадач --> СтадииТребований:ТипЗадач

    _РегистрСведений(КатегорииСпециалистовПроектов, "Категории специалистов проектов") {
        {abstract} Непереодический, независимый
        __
        <$d> Проект : Проекты
        <$d> КатегорияСпециалиста: КатегорииСпециалистов
    }
    КатегорииСпециалистов --> КатегорииСпециалистовПроектов::КатегорияСпециалиста

    _РегистрСведений(СотрудникиПроектов, "Сотрудники проектов") {
        {abstract} Непереодический, независимый
        __
        <$d> Проект : Проекты
        <$d> Сотрудник: Сотрудники
        <$d> ТипЗадач: ТипыЗадач
    }
    ТипыЗадач --> СотрудникиПроектов:ТипЗадач
    Сотрудники --> СотрудникиПроектов:Сотрудник

    _РегистрСведений(СтатьиБюджетаПроектов, "Статьи бюджета проектов") {
        {abstract} Непереодический, независимый
        __
        <$d> Проект : Проекты
        <$d> СтатьяБюджета: СтатьиБюджета
    }
    СтатьиБюджета --> СтатьиБюджетаПроектов::СтатьяБюджета
    _РегистрСведений(СистемыПроектов, "Системы проектов") {
        {abstract} Непереодический, независимый
        __
        <$d> Проект : Проекты
        <$d> Система: Системы
    }

    _РегистрСведений(ФункциональныеБлокиПроектов, "Функциональные блоки проектов") {
        {abstract} Непереодический, независимый
        __
        <$d> Проект : Проекты
        <$d> ФункциональныйБлок: ФункциональныеБлоки
    }
    ФункциональныеБлоки --> ФункциональныеБлокиПроектов::ФункциональныйБлок

    _РегистрСведений(ВидыВремениПроектов, "Виды времени проектов") {
        {abstract} Непереодический, независимый
        __
        <$d> Проект : Проекты
        <$d> ВидВремени: ВидыВремени
    }
  ВидыВремени --> ВидыВремениПроектов::ВидВремени

    _РегистрСведений(РелизыСистемПроектов, "Релизы систем проектов"){
        {abstract} Непереодический, независимый
        __
        <$d> Проект : Проекты
        <$d> Система : Системы
        <$r> Релиз: Строка (50)
    }
    Системы --> СистемыПроектов::Система
    Системы --> РелизыСистемПроектов::Система

  
    _РегистрСведений(СтадииТребованийПроектов, "Стадии требований проектов"){
        {abstract} Непереодический, независимый
        __
        <$d> Проект : Проекты
        <$d> Стадия : Стадии
        <$r> Порядок : Число(3)
    }
    СтадииТребований --> СтадииТребованийПроектов::Стадия

    Проекты --> РелизыСистемПроектов::Проект
    Проекты --> ЭтапыПроектов::Владелец
    Проекты --> ВидыВремениПроектов::Проект
    Проекты --> ФункциональныеБлокиПроектов::Проект
    Проекты --> СистемыПроектов::Проект
    Проекты --> СтатьиБюджетаПроектов::Проект
    Проекты --> СотрудникиПроектов::Проект
    Проекты --> КатегорииСпециалистовПроектов::Проект
    Проекты --> СтадииТребованийПроектов::Проект

}


















@enduml