@startuml

!include /1ce-icons-for-plantuml/dist/common.puml
!include /1ce-icons-for-plantuml/dist/all.puml

'header
title Система управления проектами
caption Бюджетная оценка
footer Софт-Юнити, 2023

_Справочник(КатегорииСпециалистов, "Категории специалистов")
_Документ(Требование, "Требование") {
  ПлановаяОценка: Число(10,2)
}
_Документ(Задача, "Задача")
_Справочник(СтадииТребований, "Стадии требований")

package "Плановая оценка" <<Cloud>> {

_РегистрНакопления(ПлановыеТрудозатраты, "Плановые трудозатраты") {
    {abstract} Обороты
    __
    Регистратор : Задача
    <$d> Требование : Требование
    <$d> СтадияТребования : СтадииТребований
    <$d> КатегорияСпециалиста : КатегорииСпециалистов
    <$r> Часы: Число (10, 2)}

}

СтадииТребований --> ПлановыеТрудозатраты::СтадияТребования
КатегорииСпециалистов --> ПлановыеТрудозатраты::КатегорияСпециалиста
Требование --> ПлановыеТрудозатраты::Требование
Задача --> ПлановыеТрудозатраты::Регистратор
Требование::ПлановаяОценка --> ПлановыеТрудозатраты::Часы

@enduml