@startuml

!include /1ce-icons-for-plantuml/dist/common.puml
!include /1ce-icons-for-plantuml/dist/all.puml

'header
title Система управления проектами
caption Релизы задач
footer Софт-Юнити, 2023

_Справочник(Проекты, "Проекты")
_Документ(Задача, "Задача")

package "Релизы задач" <<Cloud>> {

  _Справочник(Системы, "Системы")

  _Справочник(Релизы, "Релизы систем"){
    Проект : Проекты
    Система : Системы
    УстановленНаПродуктив : Булево
  }

  Системы --> Релизы::Система
  Проекты --> Релизы::Проект

  _РегистрСведений(ТекущиеРелизыСистемыПроектов, "Текущие релизы систем проектов"){
    {abstract} Непереодический, независимый
    __
    <$d> Проект : Проекты
    <$d> Система : Системы
    <$r> Релиз: Релизы
  }

  _Отчет(ЗадачиВРелизах, "Задачи в релизах")

  _Отчет(РелизыСистемПроекта, "Релизы систем проекта")

  Проекты --> ТекущиеРелизыСистемыПроектов::Проект
  Системы --> ТекущиеРелизыСистемыПроектов::Система
  Релизы --> ТекущиеРелизыСистемыПроектов::Релиз

  _Документ(СборкаРелиза, "Сборка релиза"){
    Проект
    Система
    Релиз
    __Задачи__
    Задача
  }
  Проекты --> СборкаРелиза::Проект
  Системы --> СборкаРелиза::Система
  Задача --> СборкаРелиза::Задача
  Релизы --> СборкаРелиза::Релиз

  _РегистрСведений(ЗадачиВошедшиеВРелиз, "Задачи вошедшие в релиз"){
    {abstract} Подчиненен регистратору
    __
    <$d> Регистратор : СборкаРелиза
    <$d> Релиз : Релизы
    <$d> Задача : Задача
  }
  СборкаРелиза --> ЗадачиВошедшиеВРелиз::Регистратор
  Релизы --> ЗадачиВошедшиеВРелиз::Релиз
  Задача --> ЗадачиВошедшиеВРелиз::Задача

}

@enduml