@startuml

!include /1ce-icons-for-plantuml/dist/common.puml
!include /1ce-icons-for-plantuml/dist/all.puml

'header
title Система управления проектами
caption Релизы задач
footer Софт-Юнити, 2023

_Справочник(Проекты, "Проекты")
_Документ(Задача, "Задача")

package "Релизы задач" <<Cloud>> {

  _Справочник(Системы, "Системы")

  _Справочник(Релизы, "Релизы систем"){
    Проект : Проекты
    Система : Системы
  }

  Системы --> Релизы::Система
  Проекты --> Релизы::Проект

  _РегистрСведений(ТекущиеРелизыСистемыПроектов, "Текущие релизы систем проектов"){
    {abstract} Непереодический, независимый
    __
    <$d> Проект : Проекты
    <$d> Система : Системы
    <$r> Релиз: Релизы
  }

  Проекты --> ТекущиеРелизыСистемыПроектов::Проект
  Системы --> ТекущиеРелизыСистемыПроектов::Система
  Релизы --> ТекущиеРелизыСистемыПроектов::Релиз

  _РегистрСведений(ЗадачиВошедшиеВРелиз, "Задачи вошедшие в релиз"){
    {abstract} Непереодический, независимый
    __
    <$d> Релиз : Релизы
    <$d> Задача : Задача
  }

  Релизы --> ЗадачиВошедшиеВРелиз::Релиз
  Задача --> ЗадачиВошедшиеВРелиз::Задача

}

@enduml