@startuml

!include /1ce-icons-for-plantuml/dist/common.puml
!include /1ce-icons-for-plantuml/dist/all.puml

'header
title Система управления проектами
caption Схема объектов системы
footer Софт-Юнити, 2023

_Справочник(Контрагенты, "Контрагенты"){
    Код : Строка(9)
    Наименование : Строка(100)
    ПолноеНаименование : Строка
    ИНН : Строка(50)
    КПП : Строка(9)
}

_Справочник(ДоговорыКонтрагентов, "Договоры контрагентов"){
    Владелец : Контрагенты
    Код : Строка(9)
    Наименование : Строка(100)
}

_Справочник(ВидыВремени, "Виды времени") {
    Рабочее : Булево
}

_Справочник(СтатьиБюджета, "Статьи бюджета")
_Справочник(Системы, "Системы")
_Справочник(ФункциональныеБлоки, "Функциональные блоки")
_Справочник(ВидыРабот, "Виды работ")
_Справочник(ПриоритетыРабот, "Приоритеты работ")
_Справочник(ТипыЗадач, "Типы задач")
_Справочник(ЭтапыТребований, "Этапы требований")

_Справочник(ПриоритетыТребований, "Приоритеты требований") {
    Порядок : Число(3)
}

_Перечисление(ПриоритетыЗадач, "Приоритеты задач") {
    Критичный
    Высокий
    Средний
    Низкий
}

_Справочник(Пользователи, "Пользователи") {
    Сотрудник : Сотрудники
}

_Справочник(Должности, "Должности")

_Перечисление(СтатусыСогласования, "Статусы согласования") {
    Черновик
    НаСогласовании
    Согласовано
    Отклонено
}

_Перечисление(СтатусыЗадач, "Статусы задача") {
    НеНачата
    ВРаботе
    Выполнена
    Приостановлена
    Отменена
}

_РегистрСведений(СостоянияОбъектов, "Состояния объектов") {
    {abstract} Переодический, в пределах секунды
    __
    <$d> Объект : ЛюбаяСсылка
    <$r> Статус: СтатусыСогласования
}

_РегистрСведений(_ЭтапыТребований, "Этапы требований") {
    {abstract} Переодический, в пределах секунды
    __
    <$d> Требование : Требование
    <$r> Этап: ЭтапыТребований
}

_РегистрСведений(_ПриоритетыТребований, "Приоритеты требований") {
    {abstract} Переодический, в пределах секунды
    __
    <$d> Требование : Требование
    <$r> Приоритет: ПриоритетыТребований
}

_РегистрСведений(Комменатрии, "Комментарии") {
    {abstract} Независимый, переодичность в пределах секунды
    --
    <$d> Объект : Требование, Задача
    <$r> Комментарий: Строка()
}

_Справочник(Заказы, "Заказы"){
    Владелец : ДоговорыКонтрагентов
    Проект : Проекты
    УчетПоЭтапам : Булево
}

_Справочник(Проекты, "Проекты"){
    {abstract} Необходимо подключить механизм доп. реквизитов
    __
    Владелец : Контрагенты
    Административный : Булево
    УчетПоЭтапам : Булево
}

_Справочник(ЭтапыПроектов, "Этапы проектов"){
    {abstract}Иерархический справочник
    __
    Владелец : Проекты
}

_Справочник(Сотрудники, "Сотрудники"){
    Должность : Должности
    --КатегорииСотрудника--
    КатегорияСпециалиста : КатегорииСпециалистов
}

_Справочник(КатегорииСпециалистов, "Категории специалистов"){
}

_Справочник(ВерсииОценки, "Версии оценки") {
    Контрагент : Контрагенты
    Проект : Проекты
    Требование : Требование
    ЭтапТребования : ЭтапыТребований
    Автор : Пользователи
}

_РегистрСведений(КатегорииСпециалистовПроектов, "Категории специалистов проектов") {
    {abstract} Непереодический, независимый
    __
    <$d> Проект : Проекты
    <$r> КатегорияСпециалиста: КатегорииСпециалистов
}

_РегистрСведений(ЭтапыТребованийПроектов, "Этапы требований проектов") {
    {abstract} Непереодический, независимый
    __
    <$d> Проект : Проекты
    <$r> ЭтапТребования: ЭтапыТребований
    <$r> Порядок: Число(3)
}

_РегистрСведений(СотрудникиПроектов, "Сотрудники проектов") {
    {abstract} Непереодический, независимый
    __
    <$d> Проект : Проекты
    <$r> Сотрудник: Сотрудники
}

_РегистрСведений(СтатьиБюджетаПроектов, "Статьи бюджета проектов") {
    {abstract} Непереодический, независимый
    __
    <$d> Проект : Проекты
    <$r> СтатьяБюджета: СтатьиБюджета
}

_РегистрСведений(СистемыПроектов, "Системы проектов") {
    {abstract} Непереодический, независимый
    __
    <$d> Проект : Проекты
    <$r> Система: Системы
}

_РегистрСведений(ФункциональныеБлокиПроектов, "Функциональные блоки проектов") {
    {abstract} Непереодический, независимый
    __
    <$d> Проект : Проекты
    <$r> ФункциональныйБлок: ФункциональныеБлоки
}

_РегистрСведений(ВидыВремениПроектов, "Виды времени проектов") {
    {abstract} Непереодический, независимый
    __
    <$d> Проект : Проекты
    <$r> ВидВремени: ВидыВремени
}

_Документ(Требование, "Требование"){
    ВнешнийНомер : Строка(20)
    Наименование : Строка(100)
    Описание : Строка()
    Автор : Пользователи
    Ответственный : Пользователи
    Инициатор : Пользователи
    Проект : Проекты
    ЭтапПроекта : ЭтапыПроектов
    СтатьяБюджета : СтатьиБюджета
    Система : Системы
    ФункциональныйБлок : ФункциональныеБлоки
    ВидРаботы : ВидыРабот
}


_Документ(Задача, "Задача") {
    Требование : Требование
    ДокументОснование : Требование, Задача
    ВедущаяЗадача : Задача
    Наименование : Строка(100)
    Описание : Строка()
    Автор : Пользователи
    Исполнитель : Пользователи
    ТипЗадачи : ТипыЗадач
    Гарантия : Булево
    Блокирующая : Булево
}

_РегистрСведений(_ПриоритетыЗадач, "Приоритеты задач") {
    {abstract} Независимый, переодичность в пределах секунды
    --
    <$d> Задача : Задача
    <$r> Приоритет: ПриоритетыЗадач
}

_РегистрСведений(_СтатусыЗадач, "Статусы задач") {
    {abstract} Независимый, переодичность в пределах секунды
    --
    <$d> Задача : Задача
    <$r> Статус: СтатусыЗадач
}

_Документ(РабочийОтчет, "Рабочий отчет") {
    Пользователь : Пользователи
    Требование : Требование
    Задача : Задача
    ВидВремени : ВидыВремени
    ОписаниеРабот : Строка()
    ЗатраченныеЧасы : Число (10, 2)
}

_РегистрНакопления(ФактическиеТрудозатраты, "Фактические трудозатраты") {
    Регистратор : РабочийОтчет
    <$d> Сотрудник : Сотрудники
    <$d> ЕщеИзмерения :
    <$r> Часы: Число (10, 2)
}

_РегистрНакопления(ПлановыеТрудозатраты, "Плановые трудозатраты") {
    {abstract} Обороты
    __
    Регистратор : Требование, Задача
    <$d> Проект : Проекты
    <$d> ЭтапПроекта : ЭтапыПроектов
    <$d> Требование : Требование
    <$d> ЭтапТребования : ЭтапыТребований
    <$d> Задача : Задача
    <$d> КатегорияСпециалиста : КатегорииСпециалистов
    <$r> Часы: Число (10, 2)
}

_РегистрСведений(БюджетнаяОценка, "Бюджетная оценка"){
    {abstract} Непереодический, независимый
    __
    <$d> ВерсияОценки : ВерсииОценки
    <$d> Проект : Проекты
    <$d> ЭтапПроекта : ЭтапыПроектовв
    <$d> Требование : Требование
    <$d> ЭтапТребования : ЭтапыТребований
    <$d> Задача : Задача
    <$d> КатегорияСпециалиста : КатегорииСпециалистов
    <$r> Часы: Число (10, 2)
}

_РегистрСведений(ЧисловыеПриоритетыЗадач, "Числовые приоритеты задач"){
    {abstract} Непереодический, независимый
    __
    <$d> Задача : Задача
    <$r> Приоритет: Число (3)
}

_РегистрСведений(РелизыСистемПроектов, "Релизы систем проектов"){
    {abstract} Непереодический, независимый
    __
    <$d> Проект : Проекты
    <$d> Система : Системы
    <$r> Релиз: Строка (50)
}

Контрагенты --> ДоговорыКонтрагентов::Владелец
Контрагенты --> ВерсииОценки::Контрагент

ВерсииОценки --> БюджетнаяОценка::ВерсияОценки

ДоговорыКонтрагентов --> Заказы::Владелец

Должности --> Сотрудники::Должность

Сотрудники --> Пользователи::Сотрудник
Сотрудники --> ФактическиеТрудозатраты::Сотрудник
Сотрудники --> СотрудникиПроектов::Сотрудник

Пользователи --> Требование::Автор
Пользователи --> Требование::Ответственный
Пользователи --> РабочийОтчет::Пользователь
Пользователи --> Задача::Автор
Пользователи --> Задача::Исполнитель
Пользователи --> ВерсииОценки::Автор

Проекты --> Заказы::Проект
Проекты --> РелизыСистемПроектов::Проект
Проекты --> ЭтапыПроектов::Владелец
Проекты --> Требование::Проект
Проекты --> БюджетнаяОценка::Проект
Проекты --> ПлановыеТрудозатраты::Проект
Проекты --> ВерсииОценки::Проект
Проекты --> ВидыВремениПроектов::Проект
Проекты --> ФункциональныеБлокиПроектов::Проект
Проекты --> СистемыПроектов::Проект
Проекты --> СтатьиБюджетаПроектов::Проект
Проекты --> СотрудникиПроектов::Проект
Проекты --> ЭтапыТребованийПроектов::Проект
Проекты --> КатегорииСпециалистовПроектов::Проект

ЭтапыПроектов --> Требование::ЭтапПроекта
ЭтапыПроектов --> БюджетнаяОценка::ЭтапПроекта
ЭтапыПроектов --> ПлановыеТрудозатраты::ЭтапПроекта

ЭтапыТребований --> _ЭтапыТребований::Этап
ЭтапыТребований --> ВерсииОценки::ЭтапТребования

СтатьиБюджета --> Требование::СтатьяБюджета
СтатьиБюджета --> СтатьиБюджетаПроектов::СтатьяБюджета

Системы --> Требование::Система
Системы --> СистемыПроектов::Система
Системы --> РелизыСистемПроектов::Система

ВидыРабот --> Требование::ВидРаботы

ТипыЗадач --> Задача::ТипЗадачи

ПриоритетыЗадач --> _ПриоритетыЗадач::Приоритет

ПриоритетыТребований --> _ПриоритетыТребований::Приоритет

Задача --> Комменатрии::Объект
Задача --> ПлановыеТрудозатраты::Регистратор
Задача --> РабочийОтчет::Задача
Задача --> БюджетнаяОценка::Задача
Задача --> _ПриоритетыЗадач::Задача
Задача --> _СтатусыЗадач::Задача
Задача --> ЧисловыеПриоритетыЗадач::Задача

СтатусыЗадач --> _СтатусыЗадач::Статус

Требование --> Комменатрии::Объект
Требование --> ПлановыеТрудозатраты::Регистратор
Требование --> Задача::Требование
Требование --> РабочийОтчет::Требование
Требование --> БюджетнаяОценка::Требование
Требование --> _ЭтапыТребований::Требование
Требование --> Задача::ДокументОснование
Требование --> _ПриоритетыТребований::Требование
Требование --> _ЭтапыТребований::Требование
Требование --> ВерсииОценки::Требование

РабочийОтчет --> ФактическиеТрудозатраты::Регистратор

ВидыВремени --> РабочийОтчет::ВидВремени
ВидыВремени --> ВидыВремениПроектов::ВидВремени

КатегорииСпециалистов --> БюджетнаяОценка::КатегорияСпециалиста
КатегорииСпециалистов --> КатегорииСпециалистовПроектов::КатегорияСпециалиста

ЭтапыТребований --> БюджетнаяОценка::ЭтапТребования
ЭтапыТребований --> ЭтапыТребованийПроектов::ЭтапТребования


СтатусыСогласования --> СостоянияОбъектов::Статус

ФункциональныеБлоки --> ФункциональныеБлокиПроектов::ФункциональныйБлок
ФункциональныеБлоки --> Требование::ФункциональныйБлок

@enduml