@startuml

!include /1ce-icons-for-plantuml/dist/common.puml
!include /1ce-icons-for-plantuml/dist/all.puml

header ""
title Система управления проектами
caption Схема объектов системы
footer Софт-Юнити, 2023

package НСИ <<folder>> {

    _Справочник(Контрагенты, "Контрагенты")
    Контрагенты : Код : Строка(9)
    Контрагенты : Наименование : Строка(100)
    Контрагенты : ПолноеНаименование : Строка
    Контрагенты : ИНН : Строка(50)
    Контрагенты : КПП : Строка(9)
    
    _Справочник(ДоговорыКонтрагентов, "Договоры контрагентов")
    ДоговорыКонтрагентов : Владелец : Контрагенты
    ДоговорыКонтрагентов : Код : Строка(9)
    ДоговорыКонтрагентов : Наименование : Строка(100)

  
}


Контрагенты --> ДоговорыКонтрагентов::Владелец


@enduml