@startuml

!include /1ce-icons-for-plantuml/dist/common.puml
!include /1ce-icons-for-plantuml/dist/all.puml

'header
title Система управления проектами
caption Согласование
footer Софт-Юнити, 2023

_Справочник(Пользователи, "Пользователи")

package "Согласование" <<Cloud>> {

    _Перечисление(СтатусыСогласования, "Статусы согласования") {
        Черновик
        НаСогласовании
        Согласовано
        Отклонено
    }

    _РегистрСведений(СостоянияОбъектов, "Состояния объектов") {
        {abstract} Переодический, в пределах секунды
        __
        <$d> Объект : ОпределеяемыТип - ОбъектСогласования
        <$r> Пользователь: Пользователи
        <$r> Статус: СтатусыСогласования
    }
    СтатусыСогласования --> СостоянияОбъектов::Статус
    Пользователи --> СостоянияОбъектов::Пользователь

    class "Бизнес-процесс согласования" as БизнесПроцесс

    note as N1
    Простой бизнес-процесс согласования.
    "Задание" - из БСП
    end note
}
@enduml