@startuml

!include /1ce-icons-for-plantuml/dist/common.puml
!include /1ce-icons-for-plantuml/dist/all.puml

'header
title Система управления проектами
caption Схема объектов системы
footer Софт-Юнити, 2023

package ОбщаяНСИ <<folder>> {

    _Справочник(ВидыРабочегоВремени, "Виды рабочего времени")
    _Справочник(СтатьиБюджетов, "Статьи бюджетов")
    _Справочник(Системы, "Системы")
    _Справочник(ФункциональныеБлоки, "Функциональные блоки")
    _Справочник(ВидыРабот, "Виды работ")
    _Справочник(ПриоритетыРабот, "Приоритеты работ")
    _Справочник(ТипыЗадач, "Типы задач")
    
    _Справочник(ПриоритетыБизнесЗадач, "Приоритеты бизнес-задач") {
        Порядок : Число(3)
    }

    _Перечисление(ПриоритетыЗадач, "Приоритеты задач") {
        Критичный
        Высокий
        Средний
        Низкий
    }

    _Перечисление(СтатусыРабочихОтчетов, "Статусы рабочих отчетов") {
        Черновик
        НаСогласовании
        Согласован
        Отклонен
    }

    _Справочник(Пользователи, "Пользователи") {
        Сотрудник : Сотрудники
    }

    _Справочник(Должности, "Должности")

    _Справочник(ЗначенияДополнительныхАналитик, "Значения дополнительных аналитик") {

        ДополнительнаяАналитика : ДополнительныеАналитики
        ЗначениеАналитики : Произвольный
    }

    _Перечисление(СтатусыЗадач, "Статусы задача") {
        НеНачата
        ВРаботе
        Выполнена
        Приостановлена
        Отменена
    }

}

package "Служебная НСИ" {

 _Справочник(ЗадачиПрикрепленныеФайлы, "Задачи (Прикрепленные файлы)")
 _Справочник(БизнесЗадачиПрикрепленныеФайлы, "Бизнес-задачи (Прикрепленные файлы)")

}

package "Проектная НСИ" <<folder>> {
    _Справочник(Контрагенты, "Контрагенты")
    Контрагенты : Код : Строка(9)
    Контрагенты : Наименование : Строка(100)
    Контрагенты : ПолноеНаименование : Строка
    Контрагенты : ИНН : Строка(50)
    Контрагенты : КПП : Строка(9)

    _Справочник(ДоговорыКонтрагентов, "Договоры контрагентов")
    ДоговорыКонтрагентов : Владелец : Контрагенты
    ДоговорыКонтрагентов : Код : Строка(9)
    ДоговорыКонтрагентов : Наименование : Строка(100)

    _Справочник(Заказы, "Заказы")
    Заказы : Владелец : ДоговорыКонтрагентов
    Заказы : Проект : Проекты
    Заказы : УчетПоЭтапам : Булево

    _Справочник(Проекты, "Проекты"){
        Подключить
        Владелец : Контрагенты
        УчетПоЭтапам : Булево
    }

    _Справочник(ЭтапыПроектов, "Этапы проектов"){
        Иерархический справочник
        --
    }
    ЭтапыПроектов : Владелец : Проекты

    _Справочник(Сотрудники, "Сотрудники")
    Сотрудники : Должность : Должности


    _ПВХ(ДополнительныеАналитики, "Дополнительные аналитики"){

    }

    _Справочник(КатегорииСпециалистов, "Категории специалистов"){

    }

    note as NS1
        Не знаю как сделать лучше настриваемые значения для проекта.
        Мне видится регистры сведений измерение проект ресурс значение
        Типа: Системы проекта
    end note
 
}

package Задачи <<folder>> {
    _Документ(БизнесЗадача, "Бизнес-задача"){
        ВнешнийНомер : Строка(20)
        Наименование : Строка(100)
        Описание : Строка()
        Автор : Пользователи
        Ответственный : Пользователи
        Инициатор : Пользователи
        Проект : Проекты
        ЭтапПроекта : ЭтапыПроектов
        СтатьяБюджета : СтатьиБюджетов
        Система : Системы
        ФункциональныйБлок : ФункциональныеБлоки
        Приоритет : ПриоритетыЗадач
        ВидРаботы : ВидыРабот

        -- Дополнительные аналитики --
        Аналитика : ДополнительныеАналитики
        Значение : Характеристика.ДополнительныеАналитики   
    }

    _РегистрСведений(Комменатрии, "Комментарии") {
        Независимый переодический регистр сведений.
        Переодичность - секунда
        --
        <$d> Объект : БизнесЗадача, Задача
        <$r> Комментарий: Строка() 
    }

    _Документ(Задача, "Задача") {
        БизнесЗадача : БизнесЗадача
        Наименование : Строка(100)
        Описание : Строка()
        Автор : Пользователи
        Исполнитель : Пользователи
        ТипЗадачи : ТипыЗадач
        Приоритет : ПриоритетыЗадач
        Гарантия : Булево
        Блокирующая : Булево

    }
}

package УчетВремени <<folder>> {

    package ФактическиеТрудозатраты <<folder>> {
        _Документ(РабочийОтчет, "Рабочий отчет") {
            Пользователь : Пользователи
            БизнесЗадача : БизнесЗадача
            Задача : Задача
            ВидРабочегоВремени : ВидыРабочегоВремени
            ОписаниеРабот : Строка()
            ЗатраченныеЧасы : Число (10, 2) 
        }

        _РегистрНакопления(ФактическиеТрудозатраты, "Фактические трудозатраты") {
            Регистратор : РабочийОтчет
            <$d> Сотрудник : Сотрудники
            <$d> ЕщеИзмерения : 
            <$r> Часы: Число (10, 2)
        }
     
        _РегистрСведений(СтатусыОтчетов, "Статусы рабочих отчетов") {
            <$d> РабочийОтчет : РабочийОтчет
            <$r> Статус: СтатусыРабочихОтчетов
        }
    }

    package ПлановыеТрудозатраты <<folder>> {
        
        _РегистрНакопления(ПлановыеТрудозатраты, "Плановые трудозатраты") {
            Регистратор : БизнесЗадача, Задача
            <$d> Контрагент : Контрагенты
            <$d> Проект : Проекты
            <$d> Заказ : Заказы
            <$d> ЭтапПроекта : ЭтапыПроектов
            <$d> ЕщеИзмерения : 
            <$r> Часы: Число (10, 2)
        }

        _РегистрНакопления(ЦелевыеТрудозатраты, "Целевые трудозатраты") {
            Регистратор : БизнесЗадача, Задача
            <$d> Контрагент : Контрагенты
            <$d> Проект : Проекты
            <$d> Заказ : Заказы
            <$d> ЭтапПроекта : ЭтапыПроектов
            <$d> ЕщеИзмерения : 
            <$r> Часы: Число (10, 2)
        }
    }
}

/' note as ЗаметкаСправочники
Для справочников, если не указано дополнительно
Код : Строка(9)
Наименование : Строка(100)
end note
note as ЗаметкаДокументы
Для документов, если не указано дополнительно
Запрет опреативного проведения
end note '/

Контрагенты --> ДоговорыКонтрагентов::Владелец
ДоговорыКонтрагентов --> Заказы::Владелец

Должности --> Сотрудники::Должность

Сотрудники --> Пользователи::Сотрудник
Сотрудники --> ФактическиеТрудозатраты::Сотрудник

Пользователи --> БизнесЗадача::Автор
Пользователи --> БизнесЗадача::Ответственный
Пользователи --> РабочийОтчет::Пользователь
Пользователи --> Задача::Автор
Пользователи --> Задача::Исполнитель
Пользователи --> Задача::Исполнитель

Проекты --> Заказы::Проект
Проекты --> ЭтапыПроектов::Владелец
Проекты --> БизнесЗадача::Проект

ЭтапыПроектов --> БизнесЗадача::ЭтапПроекта

СтатьиБюджетов --> БизнесЗадача::СтатьяБюджета
Системы --> БизнесЗадача::Система

ДополнительныеАналитики --> ЗначенияДополнительныхАналитик::ДополнительнаяАналитика
ДополнительныеАналитики --> БизнесЗадача::Аналитика

ВидыРабот --> БизнесЗадача::ВидРаботы

ТипыЗадач --> Задача::ТипЗадачи

ПриоритетыЗадач --> БизнесЗадача::Приоритет
ПриоритетыЗадач --> Задача::Приоритет

Задача --> Комменатрии::Объект
Задача --> ПлановыеТрудозатраты::Регистратор
Задача --> ЦелевыеТрудозатраты::Регистратор
Задача --> РабочийОтчет::Задача

БизнесЗадача --> Комменатрии::Объект
БизнесЗадача --> ПлановыеТрудозатраты::Регистратор
БизнесЗадача --> Задача::БизнесЗадача
БизнесЗадача --> РабочийОтчет::БизнесЗадача
БизнесЗадача --> ЦелевыеТрудозатраты::Регистратор

РабочийОтчет --> ФактическиеТрудозатраты::Регистратор
РабочийОтчет --> СтатусыОтчетов::РабочийОтчет

ВидыРабочегоВремени --> РабочийОтчет::ВидРабочегоВремени

СтатусыРабочихОтчетов --> СтатусыОтчетов::Статус
@enduml