@startuml

!include /1ce-icons-for-plantuml/dist/common.puml
!include /1ce-icons-for-plantuml/dist/all.puml

'header
title Система управления проектами
caption Задачи и требования
footer Софт-Юнити, 2023

_Справочник(СтатьиБюджета, "Статьи бюджета")
_Справочник(Системы, "Системы")
_Справочник(ФункциональныеБлоки, "Функциональные блоки")
_Справочник(Проекты, "Проекты")
_Справочник(ЭтапыПроектов, "Этапы проектов")
_Справочник(Пользователи, "Пользователи")
_Справочник(СтадииТребований, "Стадии требований")

package "Задачи и требования" <<Cloud>> {

    _Перечисление(ТипыЗадач, "Типы задач") {
        Управление проектом
        Аналитика
        Согласование/оценка
        Уточнение
        Управление разработкой
        Разработка
        Тестирование
        Исправление
        Приемка работ
    }
    _Перечисление(ПриоритетыЗадач, "Приоритеты задач") {
        Критичный
        Высокий
        Средний
        Низкий
    }

    _Перечисление(СтатусыЗадачИТребований, "Статусы задача и требований") {
        НеАктивна - может быть только у задачи
        НеНачата
        ВРаботе
        Выполнена
        Приостановлена
        Отменена
    }
    _Справочник(ВидыРабот, "Виды работ")


    _Справочник(ПриоритетыТребований, "Приоритеты требований") {
        Порядок : Число(3)
    }

    _Документ(Требование, "Требование"){
        {abstract} Использовать механизм доп. реквизитов
        __
        ВнешнийНомер : Строка(20)
        ВнешняяДата : Дата
        Наименование : Строка(100)
        Описание : ХранилищеЗначений
        Автор : Пользователи
        Ответственный : Пользователи
        Инициатор : Пользователи
        Проект : Проекты
        ЭтапПроекта : ЭтапыПроектов
        СтатьяБюджета : СтатьиБюджета
        Система : Системы
        ФункциональныйБлок : ФункциональныеБлоки
        ВидРаботы : ВидыРабот
        ТребуетПодтвержденияРП: Булево
    }
    ФункциональныеБлоки --> Требование::ФункциональныйБлок
    Пользователи --> Требование::Автор
    Пользователи --> Требование::Ответственный
    Проекты --> Требование::Проект
    ЭтапыПроектов --> Требование::ЭтапПроекта
    СтатьиБюджета --> Требование::СтатьяБюджета
    Системы --> Требование::Система
    ВидыРабот --> Требование::ВидРаботы

    _РегистрСведений(_СтадииТребований, "Стадии требований") {
        {abstract} Переодический, в пределах секунды
        __
        <$d> Требование : Требование
        <$r> Стадия: СтадииТребований
    }
    Требование --> _СтадииТребований::Требование
    СтадииТребований --> _СтадииТребований::Стадия

    _РегистрСведений(_ПриоритетыТребований, "Приоритеты требований") {
        {abstract} Переодический, в пределах секунды
        __
        <$d> Требование : Требование
        <$r> Приоритет: ПриоритетыТребований
    }
    Требование --> _ПриоритетыТребований::Требование
    ПриоритетыТребований --> _ПриоритетыТребований::Приоритет

    _Документ(Задача, "Задача") {
        Требование : Требование
        Стадия : Стадии
        ДокументОснование : Требование, Задача
        ВедущаяЗадача : Задача
        Наименование : Строка(100)
        Описание : ХранилищеЗначений
        Автор : Пользователи
        Исполнитель : Пользователи
        ТипЗадачи : ТипыЗадач
        Гарантия : Булево
        Блокирующая : Булево
        ПлановаяОценка : Число(10,2)
        ВключатьВРеестрОткрытыхВопросов: Булево
    }
    Пользователи --> Задача::Автор
    Пользователи --> Задача::Исполнитель
    Требование --> Задача::Требование
    Требование --> Задача::ДокументОснование
    ТипыЗадач --> Задача::ТипЗадачи

    _РегистрСведений(_ПриоритетыЗадач, "Приоритеты задач") {
        {abstract} Независимый, переодичность в пределах секунды
        --
        <$d> Задача : Задача
        <$r> Приоритет: ПриоритетыЗадач
    }
    Задача --> _ПриоритетыЗадач::Задача
    ПриоритетыЗадач --> _ПриоритетыЗадач::Приоритет

    _РегистрСведений(СтатусыОбъектов, "Статусы объектов") {
        {abstract} Независимый, переодичность в пределах секунды
        --
        <$d> Объект : Задача, Требование
        <$r> Статус: СтатусыЗадачИТребований
    }
    Задача --> СтатусыОбъектов::Объект
    Требование --> СтатусыОбъектов::Объект
    СтатусыЗадачИТребований --> СтатусыОбъектов::Статус

    _РегистрСведений(ЧисловыеПриоритетыЗадач, "Числовые приоритеты задач"){
        {abstract} Непереодический, независимый
        __
        <$d> Задача : Задача
        <$r> Приоритет: Число (3)
    }

    Задача --> ЧисловыеПриоритетыЗадач::Задача
}

@enduml