@startuml

!include /1ce-icons-for-plantuml/dist/common.puml
!include /1ce-icons-for-plantuml/dist/all.puml

'header
title Система управления проектами
caption Учет сроков
footer Софт-Юнити, 2023

_Документ(Требование, "Требование")
_Документ(Задача, "Задача") 

package "Учет сроков" <<Cloud>> {

    _РегистрСведений(СрокиВыполненияЗадач, "Сроки выполнения задач") {
        <$d> Задача : Задача
        <$r> ЦелеваяДатаЗавершения: Дата
        <$r> ПрогнознаяДатаЗавершения: Дата
        <$r> ФактическаяДатаНачала: Дата
        <$r> ФактическаяДатаОкончания: Дата
    }
    Задача --> СрокиВыполненияЗадач::Задача

    _РегистрСведений(СрокиВыполненияТребований, "Сроки выполнения требований") {
        <$d> Требование : Требование
        <$r> ЦелеваяДатаЗавершения: Дата
        <$r> ПрогнознаяДатаЗавершения: Дата
        <$r> ФактическаяДатаНачала: Дата
        <$r> ФактическаяДатаОкончания: Дата
    }
    Требование --> СрокиВыполненияТребований::Требование
    
    _РегистрСведений(ПериодыПриостановкиЗадач, "Периоды приостаноки задач") {
        <$d> Задача : Задача
        <$r> НачалоПриостановки: Дата
        <$r> ОкончаниеПриостановки: Дата
    }
     Задача --> ПериодыПриостановкиЗадач::Задача
}

@enduml