@startuml

!include /1ce-icons-for-plantuml/dist/common.puml
!include /1ce-icons-for-plantuml/dist/all.puml

'header
title Система управления проектами
caption Учет сроков
footer Софт-Юнити, 2023

_Документ(Требование, "Требование")
_Документ(Задача, "Задача")

package "Учет сроков" <<Cloud>> {

    _РегистрСведений(СрокиВыполнения, "Сроки выполнения") {
        <$d> Объект : Задача, Требование
        <$r> ЦелеваяДатаЗавершения: Дата
        <$r> ПрогнознаяДатаЗавершения: Дата
        <$r> ФактическаяДатаНачала: Дата
        <$r> ФактическаяДатаОкончания: Дата
    }
    Задача --> СрокиВыполнения::Объект
    Требование --> СрокиВыполнения::Объект

    _РегистрСведений(ПериодыПриостановки, "Периоды приостаноки") {
        <$d> Объект : Задача, Требование
        <$d> НачалоПриостановки: Дата
        <$r> ОкончаниеПриостановки: Дата
    }
    Задача --> ПериодыПриостановки::Объект
    Требование --> ПериодыПриостановки::Объект

    note as note1
    Необходимо создать поля в документах
    Задача и Требование
    Поля - Целевая дата завершения, Прогнозная дата завершения
    При их изменении записывать данных в соотвествующие регистры
    +
    При записи документа при изменении статуса и при создании писать в
    фактические даты или в периоды приостановки
    endnote
}

@enduml