@startuml

!include /1ce-icons-for-plantuml/dist/common.puml
!include /1ce-icons-for-plantuml/dist/all.puml

'header
title Система управления проектами
caption Фактические трудозатараты
footer Софт-Юнити, 2023


_Справочник(Проекты, "Проект")
_Справочник(КатегорииСпециалистов, "Категории специалистов")
_Документ(Требование, "Требование")
_Документ(Задача, "Задача")

package "Фактические трудозатараты" <<Cloud>> {

  _Справочник(Пользователи, "Пользователи") {
    Сотрудник : Сотрудники
  }
  _Справочник(Должности, "Должности")

  _Справочник(ВидыВремени, "Виды времени") {
    Рабочее : Булево
  }

  _Справочник(Сотрудники, "Сотрудники"){
    Должность : Должности
    --КатегорииСотрудника--
    КатегорияСпециалиста : КатегорииСпециалистов
  }
  Должности --> Сотрудники::Должность

  _Документ(РабочийОтчет, "Рабочий отчет") {
    Пользователь : Пользователи
    Проект : Проекты
    Требование : Требование
    Задача : Задача
    ВидВремени : ВидыВремени
    ОписаниеРабот : ХранилищеЗначений
    ЗатраченныеЧасы : Число (10, 2)
  }
  Пользователи --> РабочийОтчет::Пользователь
  Требование --> РабочийОтчет::Требование
  Задача --> РабочийОтчет::Задача
  ВидыВремени --> РабочийОтчет::ВидВремени
  Проекты --> РабочийОтчет::Проект

  _РегистрНакопления(ФактическиеТрудозатраты, "Фактические трудозатраты") {
    Регистратор : РабочийОтчет
    <$d> Сотрудник : Сотрудники
    <$d> Требование : Требование
    <$d> Задача : Задача
    <$d> ВидВремени : ВидыВремени
    <$d> КатегорияСпециалиста : КатегорииСпециалистов
    <$r> Часы: Число (10, 2)
  }
  РабочийОтчет --> ФактическиеТрудозатраты::Регистратор
  Сотрудники --> ФактическиеТрудозатраты::Сотрудник
  КатегорииСпециалистов --> ФактическиеТрудозатраты::КатегорияСпециалиста
  РабочийОтчет::ЗатраченныеЧасы --> ФактическиеТрудозатраты::Часы
  Требование --> ФактическиеТрудозатраты::Требование
  Задача --> ФактическиеТрудозатраты::Задача
  ВидыВремени --> ФактическиеТрудозатраты::ВидВремени

}

@enduml